#!/bin/bash
#SBATCH -N 1
#SBATCH -C knl
#SBATCH -q debug
#SBATCH -J cs267-hw3-starter
#SBATCH -t 00:10:00

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
srun -n 1 -c 272 --cpu_bind=cores ./kmer_hash /project/projectdirs/mp309/cs267-spr2020/hw3-datasets/smaller/small.txt test
