#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH --qos=debug
#SBATCH -J cs267-hw3-starter
#SBATCH --ntasks-per-node=60
#SBATCH -t 00:10:00


#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
srun --cpu_bind=cores ./kmer_hash_19 /global/cfs/cdirs/mp309/cs267-spr2020/hw3-datasets/smaller/small.txt
