#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J cs267-hw3-starter
#SBATCH --ntasks-per-node=60
#SBATCH -t 00:10:00
#SBATCH -S 4 # this flag means 4 cores are gonna be dedicated to the operating system overhead (you can run up to 60 tasks per node if this flag is set, to run on 64 tasks per node please comment it out and change --ntasks-per-node=64)

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
srun ./kmer_hash_19 /global/cfs/cdirs/mp309/cs267-spr2020/hw3-datasets/smaller/small.txt
